#!/bin/bash
# Regenerates Sources/SkillSwitch/OwnerSeed.swift: every owner on the current
# skills.sh ≥50k leaderboard, classified as Organization or User via the
# GitHub API. Run before a release (needs an authenticated `gh`).
set -euo pipefail
cd "$(dirname "$0")/.."

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
curl -s https://www.skills.sh/ -o "$TMP/home.html"
python3 - "$TMP/home.html" > "$TMP/owners.txt" <<'EOF'
import json, re, sys
html = open(sys.argv[1]).read().replace('\\"', '"')
best = {}
for m in re.finditer(r'\{[^{}]*?"installs":\d+[^{}]*?\}', html):
    try: e = json.loads(m.group(0))
    except: continue
    src = e.get("source", "")
    if src.count("/") != 1 or e.get("installs", 0) < 50000: continue
    sid = e["skillId"]
    if sid not in best or e["installs"] > best[sid][1]:
        best[sid] = (src, e["installs"])
print("\n".join(sorted({s.split("/")[0] for s, _ in best.values()})))
EOF

{
  echo "// Generated by tools/make-owner-seed.sh — do not edit by hand."
  echo "// Owner kinds for every skills.sh leaderboard owner at generation time."
  echo ""
  echo "enum OwnerSeed {"
  echo "    static let kinds: [String: OwnerKind] = ["
  while read -r owner; do
      kind=$(gh api "users/$owner" --jq .type 2>/dev/null || echo skip)
      case "$kind" in
          Organization) echo "        \"$owner\": .organization," ;;
          User)         echo "        \"$owner\": .user," ;;
      esac
  done < "$TMP/owners.txt"
  echo "    ]"
  echo "}"
} > Sources/SkillSwitch/OwnerSeed.swift
echo "Wrote Sources/SkillSwitch/OwnerSeed.swift ($(grep -c ':' Sources/SkillSwitch/OwnerSeed.swift) entries)"
